tcp:
	gcc -Wall -Wextra -Werror -pedantic server.c -o server
	gcc -Wall -Wextra -Werror -pedantic client.c -o client 

udp:
	gcc -Wall -Wextra -Werror -pedantic udp_server.c -o udp_server
	gcc -Wall -Wextra -Werror -pedantic udp_client.c -o udp_client
